- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create Key Pair
      amazon.aws.ec2_key:
        name: sample
        region: ap-south-1
      register: keyout

  # This will use for print key on terminal
    # - name: print key  
    #   debug:
    #     var: keyout
    
    - name: Save key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample.pem
      when: keyout.changed == True
    
    # Launch ec2-instance
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "sample"
        # vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: client-sg
        network:
          assign_public_ip: true
        image_id: ami-001843b876406202a
        exact_count: 1
        region: ap-south-1
        tags:
          Environment: Testing