---
# Playbook for Provisioning Servers

# This playbook installs and configures the NTP (Network Time Protocol) agent on CentOS and Ubuntu servers.

- name: Provisioning Servers
  hosts: all
  become: yes
  tasks:
    # Task to install NTP Agent on CentOS
    - name: Install NTP Agent on CentOS
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"   # Condition to run this task only on CentOS hosts
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    # Task to install NTP Agent on Ubuntu
    - name: Install NTP Agent on Ubuntu
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes   # Update the package cache before installing
      when: ansible_distribution == "Ubuntu"   # Condition to run this task only on Ubuntu hosts
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    # Task to start the NTP service on CentOS
    - name: Start Service on CentOS
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"   # Condition to run this task only on CentOS hosts

    # Task to start the NTP service on Ubuntu
    - name: Start Service on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"   # Condition to run this task only on Ubuntu hosts

    # Copy content to remote host's file
    - name: Banner file
      copy:
        content: '# This server is managed by ansible. No manual changes please'
        dest: /etc/motd # Content of this file will print on terminal when user login to terminal. (Message of the day)
    
    - name: Deploy NTP agent conf on centos
      template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
    
    - name: Deploy NTP agent conf on Ubuntu
      template:
        src: templates/ntpconf_ubuntu
        dest: /etc/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"
    
    # Restart services after configuration changes

    - name: ReStart Service on CentOS
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"   

    - name: ReStart Service on Ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: Create a directory that does not exists
      file:
        path: /opt/test21
        state: directory