apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure

# Below is command for execute and monitor
# kubectl apply -f com.yaml
# kubectl get pod => This will show pods in completed state because after run the command container will dead.
# kubectl logs command-demo
